CREATE SCHEMA RENTAUTO; USE RENTAUTO;

CREATE TABLE `RENTAUTO`.`Usuario`( 
`NOMBRE` VARCHAR(255)  NOT NULL,
`APELLIDO` VARCHAR(255)  NOT NULL,
`IDNOMBRE` VARCHAR(255)  NOT NULL,  
`PASSWORD` VARCHAR(255) NOT NULL,  
`FECHADENACIMIENTO` DATE,
`EMAIL` VARCHAR(255)  NOT NULL,
`CODIGODEVALIDACION` VARCHAR(255) NOT NULL,
`ESTADODEVALIDACION` TINYINT(1) NOT NULL,
 PRIMARY KEY (`IDNOMBRE`)
);

ENGINE = InnoDB;